spring.application.name=aventyrs-api

server.port=9893

spring.profiles.active=dev

spring.mongodb.uri=mongodb://localhost:27017/aventyrs

seaweedfs.filer-url=http://localhost:8888
seaweedfs.s3.endpoint=http://localhost:8333
seaweedfs.s3.access-key=${AWS_ACCESS_KEY_ID:admin}
seaweedfs.s3.secret-key=${AWS_SECRET_ACCESS_KEY:secret}
seaweedfs.s3.bucket=${S3_BUCKET:my-bucket}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
